### ISSUE TITLE
404 link from homepage to font source

### ISSUE THREAD

**Issue by gregsadetsky** [idleberg/playdate-arcade-fonts#1]
Hi!

I noticed that on

https://idleberg.github.io/playdate-arcade-fonts

when scrolling down to "Warrior Blade Rastan Saga Episode III", the "Source </>" button there leads to a 404.

Cheers and thanks for making these fonts!

**Comment by idleberg** [comment]
Thanks for posting the issue. I’m currently on vacation and will take a look when I get back end of the month!

**Comment by idleberg** [comment]
Note to self: looks like a simple name mismatch between fonts and meta data

**Comment by gregsadetsky** [comment]
Confirmed, thank you!
