### ISSUE TITLE
Include font binaries

### ISSUE THREAD

**Issue by allkern** [idleberg/playdate-arcade-fonts#2]
I've personally never used `.fnt` files, nor do I know how they are used. I think 1-bit binaries would be a more universal format for distribution of these fonts, as they could be more easily parsed and converted to other formats.

I took the time to make a [converter](https://github.com/lycoder/fnt2bin/), you are free to use this to convert every font!

**Comment by gingerbeardman** [comment]
I too am a little puzzled. These fonts will likely exist in many other formats that I don't see how it's useful to convert them from Playdate .fnt to any other format. Just find it in the other format to begin with.

**Comment by allkern** [comment]
Yes, you're right, I was actually looking for arcade fonts for another project, and didn't realize these fonts were solely for use on the Playdate.
I just found them useful beyond their intended purpose. It's all up to you if you want to include my converter in your FAQ, otherwise, I'm really grateful for this collection anyways

**Comment by idleberg** [comment]
Out of curiosity: What's a use-case for these binary fonts and how can I test those?
