### ISSUE TITLE
How to use these fonts? Are they downloadable? How to install?

### ISSUE THREAD

**Issue by nyngwang** [idleberg/playdate-arcade-fonts#3]

**Comment by gingerbeardman** [comment]
Files are in static/fonts as .fnt

These are Playdate format fonts, use them with the Playdate SDK. 

Or use [Bits'n'Picas](https://github.com/kreativekorp/bitsnpicas) to open/view/convert.

**Comment by gingerbeardman** [comment]
You can use them on computer, see my last point above. But there may be more straightforward ways.
